/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectproddigital.view;
import com.mycompany.projectproddigital.controller.ProductoController;
import javax.swing.JOptionPane;

/**
 *
 * @author shari
 */
public class ViewPrincipal extends javax.swing.JFrame {

    private ProductoController controller;
    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        controller = new ProductoController();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemInsertarEbook = new javax.swing.JMenuItem();
        itemListarEbook = new javax.swing.JMenuItem();
        itemEliminarEbook = new javax.swing.JMenuItem();
        itemCalcPreEbook = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemInsertarCurso = new javax.swing.JMenuItem();
        itemListarCurso = new javax.swing.JMenuItem();
        itemEliminarCurso = new javax.swing.JMenuItem();
        itemCalcPreCurso = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel1.setText("Bienvenido");

        jMenu1.setText("Ebook");

        itemInsertarEbook.setText("Insertar");
        itemInsertarEbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInsertarEbookActionPerformed(evt);
            }
        });
        jMenu1.add(itemInsertarEbook);

        itemListarEbook.setText("Listar");
        itemListarEbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarEbookActionPerformed(evt);
            }
        });
        jMenu1.add(itemListarEbook);

        itemEliminarEbook.setText("Eliminar");
        itemEliminarEbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarEbookActionPerformed(evt);
            }
        });
        jMenu1.add(itemEliminarEbook);

        itemCalcPreEbook.setText("Calcular precio");
        itemCalcPreEbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCalcPreEbookActionPerformed(evt);
            }
        });
        jMenu1.add(itemCalcPreEbook);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cursos Online");

        itemInsertarCurso.setText("Insertar");
        itemInsertarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInsertarCursoActionPerformed(evt);
            }
        });
        jMenu2.add(itemInsertarCurso);

        itemListarCurso.setText("Listar");
        itemListarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarCursoActionPerformed(evt);
            }
        });
        jMenu2.add(itemListarCurso);

        itemEliminarCurso.setText("Eliminar");
        itemEliminarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarCursoActionPerformed(evt);
            }
        });
        jMenu2.add(itemEliminarCurso);

        itemCalcPreCurso.setText("Calcular precio");
        itemCalcPreCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCalcPreCursoActionPerformed(evt);
            }
        });
        jMenu2.add(itemCalcPreCurso);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");

        itemAcerca.setText("Acerca de");
        itemAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAcercaActionPerformed(evt);
            }
        });
        jMenu3.add(itemAcerca);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabel1)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemInsertarEbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInsertarEbookActionPerformed
        // TODO add your handling code here:
        new ViewInsertarEbook(controller).setVisible(true);       
    }//GEN-LAST:event_itemInsertarEbookActionPerformed

    private void itemInsertarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInsertarCursoActionPerformed
        // TODO add your handling code here:
        new ViewInsertarCurso(controller).setVisible(true);
    }//GEN-LAST:event_itemInsertarCursoActionPerformed

    private void itemListarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarCursoActionPerformed
        // TODO add your handling code here:
        new ViewListar(controller).setVisible(true);
    }//GEN-LAST:event_itemListarCursoActionPerformed

    private void itemEliminarEbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarEbookActionPerformed
        // TODO add your handling code here:
        new ViewEliminar(controller).setVisible(true);
    }//GEN-LAST:event_itemEliminarEbookActionPerformed

    private void itemCalcPreEbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCalcPreEbookActionPerformed
        // TODO add your handling code here:
        new ViewCalcular(controller).setVisible(true);
    }//GEN-LAST:event_itemCalcPreEbookActionPerformed

    private void itemEliminarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarCursoActionPerformed
        // TODO add your handling code here:
        new ViewEliminar(controller).setVisible(true);
    }//GEN-LAST:event_itemEliminarCursoActionPerformed

    private void itemCalcPreCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCalcPreCursoActionPerformed
        // TODO add your handling code here:
        new ViewCalcular(controller).setVisible(true);
    }//GEN-LAST:event_itemCalcPreCursoActionPerformed

    private void itemAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAcercaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,
        "Proyecto Producto Digital\n" +
        "Versión 1.0\n\n" +
        "Integrantes:\n" +
        "Sharith Giselle Santos Guerrero\n" +
        "Linda Sofia Moreno Gonzalez \n" +
        "Yamilett Daniela Flores Respaldiza \n" +
        "Universidad de Ibagué\n" +
        "2026A");
    }//GEN-LAST:event_itemAcercaActionPerformed

    private void itemListarEbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarEbookActionPerformed
        new ViewListar(controller).setVisible(true);
    }//GEN-LAST:event_itemListarEbookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAcerca;
    private javax.swing.JMenuItem itemCalcPreCurso;
    private javax.swing.JMenuItem itemCalcPreEbook;
    private javax.swing.JMenuItem itemEliminarCurso;
    private javax.swing.JMenuItem itemEliminarEbook;
    private javax.swing.JMenuItem itemInsertarCurso;
    private javax.swing.JMenuItem itemInsertarEbook;
    private javax.swing.JMenuItem itemListarCurso;
    private javax.swing.JMenuItem itemListarEbook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
