/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.view;

import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Dhan
 */
public class ViewPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewPrincipal.class.getName());

    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        initComponents();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        itemInsertarEbook1 = new javax.swing.JMenuItem();
        itemListarEbook1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        itemCalcPreEbook1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemInsertarCurso = new javax.swing.JMenuItem();
        itemListarCurso = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        itemCalcPreCurso = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu4.setText("Ebook");

        itemInsertarEbook1.setText("Insertar");
        itemInsertarEbook1.addActionListener(this::itemInsertarEbook1ActionPerformed);
        jMenu4.add(itemInsertarEbook1);

        itemListarEbook1.setText("Listar");
        itemListarEbook1.addActionListener(this::itemListarEbook1ActionPerformed);
        jMenu4.add(itemListarEbook1);

        jMenuItem4.setText("Buscar");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        jMenu4.add(jMenuItem4);

        itemCalcPreEbook1.setText("Calcular precio");
        itemCalcPreEbook1.addActionListener(this::itemCalcPreEbook1ActionPerformed);
        jMenu4.add(itemCalcPreEbook1);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Cursos Online");

        itemInsertarCurso.setText("Insertar");
        itemInsertarCurso.addActionListener(this::itemInsertarCursoActionPerformed);
        jMenu2.add(itemInsertarCurso);

        itemListarCurso.setText("Listar");
        itemListarCurso.addActionListener(this::itemListarCursoActionPerformed);
        jMenu2.add(itemListarCurso);

        jMenuItem1.setText("Buscar");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu2.add(jMenuItem1);

        itemCalcPreCurso.setText("Calcular precio");
        itemCalcPreCurso.addActionListener(this::itemCalcPreCursoActionPerformed);
        jMenu2.add(itemCalcPreCurso);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");

        itemAcerca.setText("Acerca de");
        itemAcerca.addActionListener(this::itemAcercaActionPerformed);
        jMenu3.add(itemAcerca);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemInsertarEbook1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInsertarEbook1ActionPerformed
        ViewInsertarEbook gui = new ViewInsertarEbook();
        gui.setVisible(true);
    }//GEN-LAST:event_itemInsertarEbook1ActionPerformed

    private void itemListarEbook1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarEbook1ActionPerformed
        ViewListarEbook gui = new ViewListarEbook();
        gui.setVisible(true);
    }//GEN-LAST:event_itemListarEbook1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        ViewBuscar gui = new ViewBuscar();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void itemCalcPreEbook1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCalcPreEbook1ActionPerformed
    }//GEN-LAST:event_itemCalcPreEbook1ActionPerformed

    private void itemInsertarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInsertarCursoActionPerformed
        ViewInsertarCurso gui = new ViewInsertarCurso();
        gui.setVisible(true);
    }//GEN-LAST:event_itemInsertarCursoActionPerformed

    private void itemListarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarCursoActionPerformed
        ViewListarCurso gui = new ViewListarCurso();
        gui.setVisible(true);
    }//GEN-LAST:event_itemListarCursoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ViewBuscar gui = new ViewBuscar();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void itemCalcPreCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCalcPreCursoActionPerformed
    }//GEN-LAST:event_itemCalcPreCursoActionPerformed

    private void itemAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAcercaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,
            "Proyecto Producto Digital\n" +
            "Versión 1.0\n\n" +
            "Integrantes:\n" +
            "Sharith Giselle Santos Guerrero\n" +
            "Linda Sofia Moreno Gonzalez \n" +
            "Yamilett Daniela Flores Respaldiza \n" +
            "Universidad de Ibagué\n" +
            "2026A");
    }//GEN-LAST:event_itemAcercaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAcerca;
    private javax.swing.JMenuItem itemCalcPreCurso;
    private javax.swing.JMenuItem itemCalcPreEbook1;
    private javax.swing.JMenuItem itemInsertarCurso;
    private javax.swing.JMenuItem itemInsertarEbook1;
    private javax.swing.JMenuItem itemListarCurso;
    private javax.swing.JMenuItem itemListarEbook1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables
}
