/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.view;

import com.mycompany.model.CursoOnline;
import com.mycompany.model.ProductoDigital;
import com.mycompany.service.ProductoService;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dhan
 */
public class ViewListarCurso extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewListarCurso.class.getName());

    /**
     * Creates new form ViewListarCurso
     */
    public ViewListarCurso() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        CargarTabla();
        
    }
    
    private void CargarTabla() {
        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("Código");
        modelo.addColumn("Nombre");
        modelo.addColumn("Precio Base");
        modelo.addColumn("Tamaño (MB)");
        modelo.addColumn("Duración (H)");
        modelo.addColumn("Certificado");
    
        // Asumiendo que listarProductos() es estático según tu código original
        for (ProductoDigital e : ProductoService.listarProductos()) {
            // Verificamos que sea un CursoOnline para evitar errores de casteo
            if (e instanceof CursoOnline) {
                CursoOnline miCurso = (CursoOnline) e;
                Object[] fila = new Object[6]; // Tamaño ajustado a las columnas

                fila[0] = miCurso.getId();
                fila[1] = miCurso.getNombre();
                fila[2] = miCurso.getPrecioBase();
                fila[3] = miCurso.getTamanoMB();
                fila[4] = miCurso.getDuracionHoras();
                fila[5] = miCurso.getCertificado();
                
                modelo.addRow(fila); // ¡IMPORTANTE: Agrega la fila al modelo!
            }
        }
        // Seteamos el modelo a la tabla de la interfaz
        jTable1.setModel(modelo);
    } 
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jMenu1.setText("Listado Cursos");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    // ... (deja el bloque try-catch del look and feel como está)

    java.awt.EventQueue.invokeLater(() -> new ViewListarCurso().setVisible(true));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
